### ISSUE TITLE
Add android-HM10-screenshot

### ISSUE THREAD

**Issue by spyua** [spyua/Android-HM10-TEST#1]
![001](https://cloud.githubusercontent.com/assets/20264622/20243184/8d724b6e-a987-11e6-92c9-d0141fe753d1.png)

**Comment by mbta009** [comment]
Dear @spyua  
Thanks for posting the experience
Is it possible to download the APK file of this software?

**Comment by spyua** [comment]
> Dear @spyua
> Thanks for posting the experience
> Is it possible to download the APK file of this software?

Hi~It is my first android project for a long times.
I publish on google player https://play.google.com/store/apps/details?id=com.polkapolka.team.micro
You can try it.
